### PR TITLE
Fix corrupt gzip

### PR DESCRIPTION
**Pull request by SpecificProtagonist**
`GZEncoder::finish` wasn't being called, which can lead to corruption (seems to work for small files, but break for larger ones).

### CODE REVIEW

**Comment by mrghosti3** [comment]
In the flate2 docs, `GzEncoder` implements [`Drop`](https://docs.rs/flate2/1.0.27/flate2/write/struct.GzEncoder.html#impl-Drop-for-GzEncoder%3CW%3E). It calls finish by default when encoder goes out of scope.

**Comment by SpecificProtagonist** [comment]
Hm, it [does](https://github.com/rust-lang/flate2-rs/blob/f62ff42615861f1d890160c5f77647466505eac0/src/gz/write.rs#L164). Odd. The version without finish seems to (for certain inputs) reliably produce corrupt output, which when decompressed starts the same as output produced by `write_compound_tag`, but differs at a certain point, which results in an error trying to load it whether from Minecraft or via this crate. Yet the version with the implicit `.finish()` works reliably. I don't understand why this is the case.

**Comment by mrghosti3** [comment]
Well in that case it is better to include your changes then.

Edit: typos.

**Comment by SpecificProtagonist** [comment]
Could you elaborate? This PR encompasses my changes.

**Comment by mrghosti3** [comment]
Well since there are some cases where the `drop` isn't fully reliable and calling `finish` is means these changes should be included (either in this repo, or back-ported to forks).

**Comment by mrghosti3** [comment]
Also, did you do any tests on `ZlibEncoder`?

**Pull request closed without merging**
